### ISSUE TITLE
Split the current application into views / models

### ISSUE THREAD

**Issue by gabbianiiii** [lbighetti/cerberus#13]
My suggestion is separate the current code of Main.elm to views / models, doing this we can do a better control to events in application.

**Comment by lbighetti** [comment]
Hi @pacheco7 !
this is a good idea in general, we can do this as the app expands, so far I think it's manageable in just 1 file.

Can you clarify what you mean by ` a better control to events in application.` ?
I'm not sure I follow.

**Comment by gabbianiiii** [comment]
> Can you clarify what you mean by a better control to events in application. ?
I'm not sure I follow.

I mean about login event, clicks events, etc...
